[package]
name = "fltk-rs-kindle-sample"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
fltk = { git = "https://github.com/wait-what/fltk-rs-kindle", features = ["no-pango"] }
# fltk = { path = "./fltk-rs-kindle/fltk", features = ["no-pango"] }

[build-dependencies]
cc = "1.2.60"
